Enable back RedfishEvent feature ``` Changes added : Enabled RedfishEvent feature
Problem Statement : During upstream sync activity the RedfishEvent feature was disabled.
due to removal RFSendEvent from yaml file

Error: "Failed to create RF event log" in journal log and no events generated

Solution: RedfishEvent feature enabled it back by adding back RFSendEvent in yaml file.

Testing :
Host: 10.41.26.141
Content-Length: 409

{
  "@odata.type": "#Event.v1_7_0.Event",
  "Context": "",
  "Events": {
    "EventTimeStamp": "2024-02-16T12:43:03+00:00",
    "Message": "The resource has been created successfully.",
    "MessageId": "ResourceEvent.1.2.ResourceCreated",
    "MessageSeverity": "OK",
    "OriginOfCondition": {
      "@odata.id": "/redfish/v1/AccountService/Accounts/charkude"
    }
  },
  "Id": "1",
  "Name": "Event Log"
}
Received: POST / HTTP/1.1
Host: 10.41.26.141
Content-Length: 309

{
  "@odata.type": "#Event.v1_7_0.Event",
  "Context": "",
  "Events": {
    "EventTimeStamp": "2024-02-16T12:42:04+00:00",
    "Message": "The resource has been created successfully.",
    "MessageId": "ResourceEvent.1.2.ResourceCreated",
    "MessageSeverity": "OK"
  },
  "Id": "1",
  "Name": "Event Log"
}
Received: POST / HTTP/1.1
Host: 10.41.26.141
Content-Length: 409

{
  "@odata.type": "#Event.v1_7_0.Event",
  "Context": "",
  "Events": {
    "EventTimeStamp": "2024-02-16T12:42:10+00:00",
    "Message": "The resource has been removed successfully.",
    "MessageId": "ResourceEvent.1.2.ResourceRemoved",
    "MessageSeverity": "OK",
    "OriginOfCondition": {
      "@odata.id": "/redfish/v1/AccountService/Accounts/charkude"
    }
  },
  "Id": "1",
  "Name": "Event Log"
}
Received: POST / HTTP/1.1
Host: 10.41.26.141
Content-Length: 510

{
  "@odata.type": "#Event.v1_7_0.Event",
  "Context": "",
  "Events": {
    "EventTimeStamp": "2024-02-16T12:43:20+00:00",
    "Message": "The property UserEnabled was assigned the value '0' due to modification by the service.",
    "MessageArgs": [
      "UserEnabled",
      "0"
    ],
    "MessageId": "Base.1.15.PropertyValueModified",
    "MessageSeverity": "OK",
    "OriginOfCondition": {
      "@odata.id": "/redfish/v1/AccountService/Accounts/charkude"
    }
  },
  "Id": "1",
  "Name": "Event Log"
}
```
Fixes jira https://jirasw.nvidia.com/browse/DGXOPENBMC-9912